#!/usr/bin/env python
# Copyright (c) 2010-2013 Turbulenz Limited
"""
Convert Collada (.dae) files into a Turbulenz JSON asset.
"""

from turbulenz_tools.tools.dae2json import main

if __name__ == "__main__":
    exit(main())
