#!/usr/bin/env python
# Copyright (c) 2010-2013 Turbulenz Limited
"""
Convert Effect Yaml (.effect) files into a Turbulenz JSON asset.
"""

from turbulenz_tools.tools.stdtool import standard_main
from turbulenz_tools.tools.effect2json import parse, __version__, __dependencies__

if __name__ == "__main__":
    standard_main(parse, __version__,
                  "Convert Effect Yaml (.effect) files into a Turbulenz JSON asset.",
                  __dependencies__)
