#!/usr/bin/env python
# Copyright (c) 2012-2013 Turbulenz Limited
"""
Generate a plain text or html output from a JSON asset.
"""

from turbulenz_tools.tools.json2txt import main

if __name__ == "__main__":
    exit(main())
