#!/usr/bin/env python
# Copyright (c) 2012-2013 Turbulenz Limited
"""
Generate a TAR file for binary assets referenced from a JSON asset.
"""

from turbulenz_tools.tools.json2tar import main

if __name__ == "__main__":
    exit(main())
